version: '3.8'

services:
  irr:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --bind :8000 irr_api.wsgi:application --reload"
    volumes:
      - ..:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tamkin123
      - POSTGRES_DB=irr-api-db

volumes:
  postgres_data: