# Generated by Django 5.0.6 on 2024-06-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('user_position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistertoken',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_position.userposition'),
            preserve_default=False,
        ),
    ]
