# Generated by Django 5.0.6 on 2024-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
