# Generated by Django 5.0.6 on 2024-05-17 06:15

from django.db import migrations


class Migration(migrations.Migration):
    def insert_data(apps, schema_editor):
        obs_type = apps.get_model('report', 'ObservationType')
        obs_factor = apps.get_model('report', 'ObservationFactor')
        obs_category = apps.get_model('report', 'ObservationCategory')
        obs_status = apps.get_model('report', 'ObservationStatus')

        obs_type.objects.bulk_create([
            obs_type(name='Neqativ'),
            obs_type(name='Pozitiv'),
        ])

        obs_factor.objects.bulk_create([
            obs_factor(name='Personal'),
            obs_factor(name='Administrativ'),
            obs_factor(name='Avadanlıq'),
            obs_factor(name='Ətraf Mühit'),
            obs_factor(name='Mal-Material'),
            obs_factor(name='İş Texnologiyası'),
        ])

        obs_category.objects.bulk_create([
            obs_category(name='Boya izolyasiya'),
            obs_category(name='Santexnika'),
            obs_category(name='Metal Konstruksiya'),
            obs_category(name='Daşıma və Ştabelləmə'),
            obs_category(name='Boru Kəməri'),
            obs_category(name='İnşaat İşləri'),
            obs_category(name='Svay işləri'),
            obs_category(name='Qaynaq'),
            obs_category(name='Elektrik'),
            obs_category(name='Digər'),
        ])

        obs_status.objects.bulk_create([
            obs_status(name='Açıq'),
            obs_status(name='Bağlı'),
        ])

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
