# Generated by Django 5.0.6 on 2024-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_create_static_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
